"""Instantaneous Stokes torque balance for whole plates.

The Reynolds number of the lithosphere is ~1e-20. Velocity is not integrated
from an acceleration; it is whatever makes the forces sum to zero at this
instant, and it changes discontinuously when the forces do. So there is no
inertia here, no velocity relaxation, no carried omega, no speed cap and no
by-fiat removal of net rotation. omega is solved from scratch every step and a
warm start changes only the iteration count, never the answer. Do not
reintroduce a lag: the measured spectral radius of explicitly coupling these
boundaries plate-by-plate is 26 (four plates) to 499, so a lagged coupling
diverges and a relaxation time only hides the divergence behind a filter.

Forces are SUMMED over the boundary where they act. A plate with 6,000 km of
trench is pulled by 6,000 km of slab. The retired raster law divided each
driver by the number of contributing edges, which made a plate's drive depend
on how finely its boundary happened to be meshed and silently cancelled
opposing segments before any constitutive law saw them.

STRUCTURE. The unknown is x_p = omega_p * R / v0, so that a relative velocity
reads directly in cm/yr and the conditioning does not depend on the radius.
The functional is convex:

    Phi(x) = 1/2 x.K x - T.x + sum_e D_e(x)

K collects the genuinely viscous resistances (asthenosphere drag under every
cell, slab Stokes drag and slab anchoring at trenches, hinge bending), T the
drivers (slab weight, ridge push, and the rigid share of the collision GPE),
and D_e the rate-independent plastic elements (megathrust, strike-slip,
distributed compression, and the suture weld). Plastic terms are regularised
and the regulariser is continued down 100/10/1/0.1 km/Myr. This is a finite
smoothing width, not evidence of convergence to the plastic limit. Relative
motion below that scale can be regularisation creep and needs a refinement
check. K is symmetric positive definite and the potentials are convex.

Constitutive version 1 uses passive one-sided compression and megathrust
laws: no normal traction is generated by opening. Version 0 preserves the
historical smooth-tail law for existing checkpoints; that law can supply
negative resisting work and must not be interpreted as passive friction.
Actual resisting work x.grad(D) is reported separately from the potential D.

WHAT IS NOT MODELLED, stated so nothing here is mistaken for a measurement:
slab dip (fixed, see slab_memory.SUBDUCTION_DIP_DEG), slab tip depth, along-slab
age structure, lower-mantle slab support, trench suction as a separate term,
sediment supply at the interface, and any intraplate stress field. Every
coefficient below carries a literature bracket in its comment; none of them is
derivable from this model's own state.
"""
from __future__ import annotations

import math
import numpy as np

import collision_contacts
import enhanced_rifting
import gravitational_relaxation
import slab_memory

VERSION = 1
RADIUS_KM = 6371.
RADIUS_M = RADIUS_KM*1e3
SECONDS_PER_YR = 365.25*86400.
SECONDS_PER_MYR = SECONDS_PER_YR*1e6
CM_YR_M_S = .01/SECONDS_PER_YR                 # one cm/yr in m/s
KM_MYR_CM_YR = .1                              # one km/Myr in cm/yr

# Asthenosphere shear traction per unit velocity, eta_a/h_a. Conrad & Behn
# (2010, G-cubed 11 Q05W05) bracket the asthenosphere at eta_a 1e19-1e21 Pa s
# over h_a 100-200 km, i.e. 5e13 to 1e16 Pa s/m; 1e15 is eta_a 1e20 over 100 km.
# EVERY absolute plate speed in this model scales as its inverse, and the only
# observable that pins it is the net-rotation bound below, so it is a
# calibration against one number across a literature range of a factor of 200.
ASTHENOSPHERE_DRAG_PA_S_M = 1.0e15
# Continental keels drag more than ocean. Conrad & Lithgow-Bertelloni (2006,
# Geology 34 541) need a 2-6x viscosity contrast under cratons to reproduce
# observed continental drift; indexed by s.crust (0 ocean, 1 continental,
# 2 craton, 3 arc).
KEEL = (1.0, 1.5, 3.5, 1.0)
# C*eta_um for a slab sinking through the upper mantle: the Stokes resistance on
# the slab and additional anchoring resistance on the overriding plate are
# separate reduced mantle-resistance closures. Conrad & Hager
# (1999, JGR 104 17551) use C ~ 1-3 with eta_um 1e21-1e22 Pa s; 3e22 Pa s sits at
# the stiff end, which is where the net-rotation bound puts it.
SLAB_STOKES_PA_S = 3.0e22
SLAB_ANCHOR_PA_S = 3.0e22
# Resistance grows with retained slab length so that terminal speed does not.
# Without it a longer slab both pulls harder and is resisted the same, and plate
# speed runs away with slab length instead of saturating.
SLAB_REFERENCE_LENGTH_KM = slab_memory.MAX_SLAB_LENGTH_KM
# Hinge bending of the descending plate, Conrad & Hager's (2/3) eta_L (h/R_b)^3
# per metre of trench. eta_L 5e22 Pa s and R_b 250 km are their fitted values;
# the cubic makes this the most uncertain resistance in the set, since h itself
# comes from a cooling law rather than a measured elastic thickness.
HINGE_VISCOSITY_PA_S = 5.0e22
BEND_RADIUS_M = 250.0e3
PLATE_THICKNESS_CAP_KM = 100.
THERMAL_DIFFUSIVITY_M2_S = 1e-6
# Megathrust shear resistance: ~15 MPa over ~120 km of down-dip contact. Heat
# flow and force-balance estimates of the average subduction interface shear
# stress cluster at 10-30 MPa (Wang & He 1999; Lamb 2006, JGR 111 B07401), an
# order of magnitude below Byerlee, so this is the weak-interface value.
MEGATHRUST_N_PER_M = 1.8e12
# Depth-averaged shear stress on a strike-slip boundary, over the seismogenic
# thickness computed from the same cooling law. San Andreas heat-flow bound
# (Lachenbruch & Sass 1980): 10-20 MPa.
TRANSFORM_SHEAR_PA = 15.0e6
TRANSFORM_DEPTH_CAP_KM = 30.
CONTINENTAL_SEISMOGENIC_KM = 15.
# Integrated strength of cold continental lithosphere resisting distributed
# shortening away from a trench (McKenzie 1977; Mueller & Phillips 1991). Same
# order as enhanced_rifting.F_REF_N_PER_M, which is the same rock.
COMPRESSIVE_N_PER_M = 1.0e13
# Cap on the suture weld's per-metre capacity. The strongest continental
# lithosphere integrates to ~1.4e13 N/m (Burov & Watts 2006); a weld cannot be
# stronger than the rock on either side of it.
WELD_CAPACITY_CAP_N_PER_M = 1.4e13
# Ridge push, as the thermal body force that produces it rather than as a force
# applied at ridges: a horizontal gradient of the cooling lithosphere's
# gravitational potential energy, distributed over the ocean floor where the age
# gradient actually is. Turcotte & Schubert (2002, eq. 6.406) integrate the same
# potential to 2-3e12 N/m for lithosphere aged to 100 Myr; with the constants
# below the law returns ~4e12 N/m there, so this driver carries a factor ~1.5
# uncertainty dominated by the choice of T_1.
MANTLE_DENSITY_KG_M3 = 3300.
WATER_DENSITY_KG_M3 = 1030.
THERMAL_EXPANSIVITY_1_K = 3e-5
MANTLE_EXCESS_TEMPERATURE_K = 1300.
GRAVITY_M_S2 = 9.81
RIDGE_PUSH_SATURATION_MYR = 100.
# Finite regularisation of the plastic terms. Small relative velocities can
# depend on this width; a force residual alone does not verify a plastic limit.
HUBER_CONTINUATION_KM_MYR = (100., 10., 1., .1)
SECANT_REFERENCE_CM_YR = 5.
ARMIJO = 1e-4
MAX_NEWTON_ITERATIONS = 60
FORCE_RELATIVE_TOLERANCE = 1e-9
# Reported, never imposed. Observed lithospheric net rotation is 0.1-0.26
# deg/Myr depending on the reference frame (Argus & Gordon 1991; Becker 2008).
# The retired law subtracted an area-weighted mean spin by fiat, which is not
# that metric and which no force produces.
NET_ROTATION_BOUND_DEG_MYR = .26


def enabled(s):
    return getattr(s, 'plate_balance_version', 0) == VERSION


def resistance_version(s):
    """Missing state deliberately retains the recorded historical law."""
    version = getattr(s, 'plate_resistance_version', 0)
    if (isinstance(version, (bool, np.bool_))
            or not isinstance(version, (int, np.integer)) or version not in (0, 1)):
        raise ValueError('Unsupported plate resistance constitutive version.')
    return int(version)


def subduction_response_version(s):
    """Saved state selects the closure; old checkpoints keep fixed-trench work."""
    version = getattr(s, 'subduction_response_version', 0)
    if (isinstance(version, (bool, np.bool_))
            or not isinstance(version, (int, np.integer)) or version not in (0, 1)):
        raise ValueError('Unsupported subduction response version.')
    return int(version)


def _unit(value):
    value = np.asarray(value, float)
    return value/np.maximum(np.linalg.norm(value, axis=-1, keepdims=True), 1e-30)


def _cell_rotation_metric(mesh):
    """Exact area mean of I-r*r.T on each great-circle triangular face.

    A centroid gives zero drag for rotation about a lone cell's radial axis.
    On the unit sphere, Laplacian(r_i*r_j)=2*delta_ij-6*r_i*r_j;
    integrating its boundary flux recovers the finite-cell second moment.
    """
    triangle = np.asarray(mesh['vertices'], float)[np.asarray(mesh['faces'], int)]
    a, b, c = triangle.transpose(1, 0, 2)
    determinant = np.einsum('ij,ij->i', a, np.cross(b, c))
    denominator = (1. + np.einsum('ij,ij->i', a, b)
                   + np.einsum('ij,ij->i', b, c)
                   + np.einsum('ij,ij->i', c, a))
    area = 2.*np.arctan2(determinant, denominator)
    if not np.isfinite(area).all() or np.any(area <= 0.):
        raise ValueError('Basal drag requires outward finite spherical cells.')
    boundary = np.zeros((len(triangle), 3, 3))
    for i, j in ((0, 1), (1, 2), (2, 0)):
        a, b = triangle[:, i], triangle[:, j]
        cross = np.cross(a, b)
        length = np.linalg.norm(cross, axis=1)
        outward = -cross/length[:, None]
        integral = (a+b)*(length/(1.+np.einsum('ij,ij->i', a, b)))[:, None]
        term = np.einsum('ci,cj->cij', outward, integral)
        boundary += term+term.transpose(0, 2, 1)
    return (2./3.)*np.eye(3)[None, :, :]+boundary/(6.*area[:, None, None])


def plate_thickness_m(age_myr, cap_km):
    """Half-space thickness at ~90% of mantle temperature (2.32 sqrt(kt)), capped.

    This is about 1,214 C for a 1,350 C mantle and a zero-C surface, not 1,100 C.
    The coefficient is retained as the existing bending calibration.
    """
    age = np.maximum(np.asarray(age_myr, float), 0.)
    return np.minimum(2.32*np.sqrt(THERMAL_DIFFUSIVITY_M2_S*age*SECONDS_PER_MYR), cap_km*1e3)


def seismogenic_depth_m(age_myr, cap_km):
    """Depth of the 600 C isotherm for half-space cooling with T_m = 1,350 C."""
    age = np.maximum(np.asarray(age_myr, float), .5)
    return np.minimum(.82*np.sqrt(THERMAL_DIFFUSIVITY_M2_S*age*SECONDS_PER_MYR), cap_km*1e3)


def ridge_push_coefficient():
    """Force per metre per second of plate age, Turcotte & Schubert eq. 6.406."""
    excess = MANTLE_DENSITY_KG_M3*THERMAL_EXPANSIVITY_1_K*MANTLE_EXCESS_TEMPERATURE_K
    correction = 1.+2.*excess/(math.pi*(MANTLE_DENSITY_KG_M3-WATER_DENSITY_KG_M3))
    return GRAVITY_M_S2*excess*THERMAL_DIFFUSIVITY_M2_S*correction


def ridge_force_density(s):
    """Tangent ridge-push body force per cell, N/m^2 (None without a native mesh).

    The horizontal gradient of the cooling plate's potential energy over ocean
    cells whose same-plate neighbours differ in age. Shared by the rigid balance
    and by diagnostics that need the distributed force rather than its torque.
    """
    mesh = getattr(s, 'native_mesh', None)
    if not isinstance(mesh, dict) or 'edge_faces' not in mesh:
        return None
    coefficient = ridge_push_coefficient()
    age = np.minimum(np.asarray(s.age, float), RIDGE_PUSH_SATURATION_MYR)*SECONDS_PER_MYR
    points = np.asarray(s.xyz, float)
    ocean = np.asarray(s.crust) == 0
    a, b = np.asarray(mesh['edge_faces']).T
    take = (s.plate[a] == s.plate[b]) & ocean[a] & ocean[b]
    a, b = a[take], b[take]
    moment = np.zeros((len(points), 3, 3))
    right = np.zeros((len(points), 3))
    for here, there in ((a, b), (b, a)):
        offset = (points[there]-points[here])*RADIUS_M
        offset -= points[here]*np.sum(offset*points[here], axis=1)[:, None]
        np.add.at(moment, here, np.einsum('ci,cj->cij', offset, offset))
        np.add.at(right, here, offset*(age[there]-age[here])[:, None])
    # Least-squares tangent gradient per cell, with the radial direction
    # pinned so an isolated cell cannot invent an out-of-plane gradient.
    trace = np.maximum(np.trace(moment, axis1=1, axis2=2), 1e-30)
    moment += np.einsum('c,ci,cj->cij', trace, points, points)
    moment += 1e-12*trace[:, None, None]*np.eye(3)
    gradient = np.linalg.solve(moment, right[..., None])[..., 0]
    gradient[~ocean] = 0.
    return coefficient*gradient


def net_rotation_deg_myr(s, omega):
    """Lithospheric net rotation by the standard no-net-rotation tensor.

    The NNR condition is that the integral of r x v over the surface vanishes,
    which for rigid plates is (sum_p J_p) w = sum_p J_p omega_p with
    J_p = sum_cells A (I - r r^T). An area-weighted mean of omega -- what the
    retired law removed -- is a different quantity and is not this bound.
    """
    total = np.zeros((3, 3))
    driven = np.zeros(3)
    support = getattr(s, 'support', None)
    plates = np.flatnonzero(s.active) if support is not None else np.unique(s.plate)
    for plate in plates:
        fraction = np.asarray(support[plate], float) if support is not None else (s.plate == plate).astype(float)
        select = fraction > 0.
        weight = np.asarray(s.cell_area, float)[select]*fraction[select]
        points = np.asarray(s.xyz, float)[select]
        tensor = np.eye(3)*weight.sum()-np.einsum('c,ci,cj->ij', weight, points, points)
        total += tensor
        driven += tensor@np.asarray(omega[int(plate)], float)
    spin = np.linalg.solve(total, driven)
    return float(np.degrees(np.linalg.norm(spin))), spin


def _abs_terms(value, delta):
    """Regularized |v|: value, first and second derivative with respect to v."""
    root = np.sqrt(value*value+delta*delta)
    # Rationalize the difference so tiny speeds retain their potential decrease.
    return value*value/(root+delta), value/root, delta*delta/root**3


def _negative_terms(value, delta):
    """Historical smooth tail, retained for version 0; NOT a passive law."""
    root = np.sqrt(value*value+delta*delta)
    return .5*(root-value)-.5*delta, .5*(value/root-1.), .5*delta*delta/root**3


def _passive_negative_terms(value, delta):
    """C1 one-sided Huber potential with exactly zero traction on opening.

    With c=max(-v,0), D=c*c/(2*delta) for c<delta and c-delta/2
    otherwise. At the two C1 joins the returned curvature is the zero-sided
    generalized derivative; the potential and force remain continuous.
    """
    closing = np.maximum(-value, 0.)
    value = np.asarray(value)
    term = np.where(closing < delta, closing*closing/(2.*delta), closing-.5*delta)
    first = -np.minimum(closing/delta, 1.)
    second = np.where((value < 0.) & (closing < delta), 1./delta, 0.)
    return term, first, second


def _cone_closing_terms(opening, width, version):
    """Closing speed for the vector norm, never a shifted potential."""
    if version == 1:
        # Squaring the positive part inside the norm makes its potential C1
        # at zero normal motion. The zero-sided Hessian is valid at that join.
        return (np.maximum(-opening, 0.), np.where(opening < 0., -1., 0.),
                np.zeros_like(opening))
    closed, first, second = _negative_terms(opening, width)
    return closed+.5*width, first, second


class Balance:
    """One step's assembled force balance. Holds no state between steps."""

    def __init__(self, s, dt, *, slab_tethers=False):
        # Explicit frozen-state experiment until the corresponding event and
        # continental-entry policy is integrated. No saved world enables this.
        if type(slab_tethers) is not bool:
            raise ValueError('Slab attachment assembly must be explicitly selected.')
        import effective_subduction
        self.effective_subduction = effective_subduction.enabled(s)
        if self.effective_subduction and slab_tethers:
            raise ValueError('Effective subduction cannot also assemble detailed slab attachments.')
        self.slab_tethers = slab_tethers
        self.uses_force_ledger = slab_tethers or self.effective_subduction
        self.s, self.dt = s, float(dt)
        self.resistance_version = resistance_version(s)
        if self.effective_subduction and self.resistance_version != 1:
            raise ValueError('Effective subduction requires passive plate resistance.')
        self.subduction_response_version = subduction_response_version(s)
        if self.subduction_response_version and self.resistance_version != 1:
            raise ValueError('Moving-hinge subduction requires passive plate resistance.')
        if self.subduction_response_version and np.any(
                np.asarray(getattr(s, 'trench_retreat_speed', ()), float) != 0.):
            raise ValueError('Moving-hinge subduction cannot add independent heuristic trench retreat.')
        self.plates = [int(p) for p in np.flatnonzero(s.active)]
        self.slot = {p: i for i, p in enumerate(self.plates)}
        self.count = len(self.plates)
        self.size = 3*self.count
        self.notes = {}
        self.elements = []
        self.drivers = {}
        self.weld_rows = []
        self.partition = None
        self._geometry()
        self._viscous()
        self._drive()
        self._plastic()
        import entry_regions
        if entry_regions.enabled(s):
            if not slab_tethers:
                raise ValueError('Persistent entry requires explicitly coupled slab attachment forces.')
            spec=entry_regions.specification(s)
            if spec is not None:
                import continental_entry
                continental_entry.apply_to_balance(self,**spec)

    # ---------------------------------------------------------------- geometry
    def _block(self, plate, vector, row):
        index = self.slot.get(int(plate))
        if index is None:
            return False
        row[3*index:3*index+3] += vector
        return True

    def _relative_rows(self, edges):
        """Normal and tangential relative-velocity rows, cm/yr, for given edges."""
        normal = np.zeros((len(edges), self.size))
        tangent = np.zeros((len(edges), self.size))
        for k, e in enumerate(edges):
            self._block(self.bq[e], self.an[e], normal[k])
            self._block(self.bp[e], -self.an[e], normal[k])
            self._block(self.bq[e], self.at[e], tangent[k])
            self._block(self.bp[e], -self.at[e], tangent[k])
        return normal, tangent

    def _absolute_rows(self, edges, owners):
        """One-sided normal-velocity rows: the named plate's own motion."""
        rows = np.zeros((len(edges), self.size))
        for k, (e, owner) in enumerate(zip(edges, owners)):
            self._block(owner, self.an[e], rows[k])
        return rows

    def _geometry(self):
        s = self.s
        self.radial = _unit(s.bmid)
        self.normal = _unit(s.bn)
        self.length_m = np.asarray(s.bl, float)*1e3
        # v_n = an.(x_q - x_p) with bn pointing from bp to bq, so positive is
        # opening, exactly as native_engine's own normal_speed measures it.
        self.an = np.cross(self.radial, self.normal)
        self.at = -self.normal
        self.bp, self.bq = np.asarray(s.bp, int), np.asarray(s.bq, int)
        self.live = np.flatnonzero((self.length_m > 1e-7)
                                   & np.isin(self.bp, self.plates) & np.isin(self.bq, self.plates))
        if self.effective_subduction:
            import effective_subduction
            self.slab_owner, self.effective_line_force, self.trench = effective_subduction.line_state(s)
            import effective_subduction_carrier_traction as carrier
            self.effective_carrier_enabled = carrier.enabled(s)
            self.effective_carrier_owner, self.effective_carrier_alpha = carrier.carriers(
                s, self.slab_owner, self.effective_line_force, self.trench)
            self.trench = self.trench & (self.slab_owner >= 0) & (self.effective_line_force > 0.)
            # Absent slab inventory stays absent: these compatibility arrays
            # carry no force, depth, mass or resistance in the effective mode.
            self.slab_load = np.zeros(len(self.bp))
            self.slab_length = np.zeros(len(self.bp))
        else:
            self.slab_owner, self.slab_load, self.slab_length = slab_memory.line_load(s)
            self.trench = (self.slab_owner >= 0) & (self.slab_load > 0.)
        if self.slab_tethers:
            import slab_tether_forces
            self.tether_assembly = slab_tether_forces.prepare(self)
            self.slab_owner = self.tether_assembly['owners']
            self.slab_load = self.tether_assembly['loads']
            self.slab_length = self.tether_assembly['extents']
        if self.slab_tethers:
            self.trench = (self.slab_owner >= 0) & (self.slab_length > 0.)
        self.strength = enhanced_rifting.edge_strength(s)

    # --------------------------------------------------------------- viscous K
    def _support(self, plate):
        """The fractional footprint that native transport actually carries."""
        support = getattr(self.s, 'support', None)
        if support is None:
            return (np.asarray(self.s.plate) == plate).astype(float)
        weight = np.asarray(support[plate], float)
        if (weight.shape != np.asarray(self.s.cell_area).shape
                or not np.isfinite(weight).all() or np.any(weight < 0.)):
            raise ValueError('Plate resistance requires finite nonnegative support.')
        return weight

    def _viscous(self):
        s = self.s
        self.stiffness = np.zeros((self.size, self.size))
        area_m2 = np.asarray(s.cell_area, float)*1e6
        keel = np.asarray(KEEL, float)[np.clip(np.asarray(s.crust, int), 0, len(KEEL)-1)]
        drag = ASTHENOSPHERE_DRAG_PA_S_M*keel
        points = np.asarray(s.xyz, float)
        cell_metric = (_cell_rotation_metric(s.native_mesh)
                       if hasattr(s, 'native_mesh') else None)
        self.basal = {}
        for plate in self.plates:
            fraction = self._support(plate)
            select = fraction > 0.
            weight = drag[select]*area_m2[select]*fraction[select]
            if cell_metric is None:
                local = points[select]
                block = (np.eye(3)*weight.sum()
                         - np.einsum('c,ci,cj->ij', weight, local, local))
            else:
                block = np.einsum('c,cij->ij', weight, cell_metric[select])
            block *= CM_YR_M_S**2
            index = self.slot[plate]
            self.stiffness[3*index:3*index+3, 3*index:3*index+3] += block
            self.basal[plate] = block
        import collision_interface
        collision_interface.assemble(self)
        usable = np.zeros(len(self.bp), bool)
        usable[self.live] = True
        trench = np.flatnonzero(self.trench & usable)
        self.trench_edges = trench
        self.hinge = np.zeros((0, self.size))
        self.hinge_coefficient = np.zeros(0)
        self.slab_horizontal_rows = np.zeros((0, self.size))
        self.slab_vertical_rows = np.zeros((0, self.size))
        self.slab_stokes_coefficient = np.zeros(0)
        self.slab_anchor_rows = np.zeros((0, self.size))
        self.slab_anchor_coefficient = np.zeros(0)
        if not len(trench):
            self.notes['trench_edges'] = 0
            return
        owners = self.slab_owner[trench]
        if not self.effective_subduction:
            self._slab_resistance(trench, owners)
        normal, _ = self._relative_rows(trench)
        below = np.where(owners == self.bp[trench], np.asarray(self.s.ba)[trench],
                         np.asarray(self.s.bb)[trench])
        thickness = plate_thickness_m(np.asarray(s.age, float)[below], PLATE_THICKNESS_CAP_KM)
        bend = (2./3.)*HINGE_VISCOSITY_PA_S*(thickness/BEND_RADIUS_M)**3
        self.hinge = normal
        self.hinge_coefficient = bend*self.length_m[trench]*CM_YR_M_S**2
        self.notes['trench_edges'] = int(len(trench))
        if not self.effective_subduction:
            self.notes['slab_length_km_mean'] = float(np.mean(self.slab_length[trench]))

    def _slab_resistance(self, trench, owners):
        """Detailed unresolved slab/neck resistance, absent in effective mode."""
        s = self.s
        others = np.where(owners == self.bp[trench], self.bq[trench], self.bp[trench])
        # Both closures retain absolute mantle resistance. Version 1 derives
        # slab velocity from the same translating fixed-dip geometry as its
        # gravitational work: h = u_over + (u_down-u_over)*cos(dip),
        # z = (u_down-u_over)*sin(dip). Their squared norm is passive and
        # still resists common translation. A relative-only drag would not.
        scale = np.clip(self.slab_length[trench]/SLAB_REFERENCE_LENGTH_KM, 0., 1.)
        down_rows = self._absolute_rows(trench, owners)
        over_rows = self._absolute_rows(trench, others)
        stokes = SLAB_STOKES_PA_S*scale*self.length_m[trench]*CM_YR_M_S**2
        anchor = SLAB_ANCHOR_PA_S*scale*self.length_m[trench]*CM_YR_M_S**2
        if getattr(self, 'subduction_response_version', subduction_response_version(s)) == 1:
            dip = math.radians(slab_memory.SUBDUCTION_DIP_DEG)
            horizontal = math.cos(dip)*down_rows+(1.-math.cos(dip))*over_rows
            vertical = math.sin(dip)*(down_rows-over_rows)
        else:
            horizontal = down_rows
            vertical = np.zeros_like(down_rows)
        self.slab_horizontal_rows, self.slab_vertical_rows = horizontal, vertical
        self.slab_stokes_coefficient = stokes
        self.slab_anchor_rows, self.slab_anchor_coefficient = over_rows, anchor
        if getattr(self, 'slab_tethers', False):
            self.stiffness += self.tether_assembly['stiffness']
        else:
            for rows in (horizontal, vertical):
                self.stiffness += np.einsum('e,ei,ej->ij', stokes, rows, rows)
        self.stiffness += np.einsum('e,ei,ej->ij', anchor, over_rows, over_rows)

    # ----------------------------------------------------------------- drivers
    def _drive(self):
        s = self.s
        self.torque = np.zeros(self.size)
        pull = np.zeros(self.size)
        reaction = np.zeros(self.size)
        dip = math.radians(slab_memory.SUBDUCTION_DIP_DEG)
        trench = self.trench_edges
        if len(trench):
            owners = self.slab_owner[trench]
            # Inextensible feeding lowers slab material at q*sin(dip), giving
            # W*sin(dip) as the work-conjugate drive. Version 0 uses q=u_down;
            # version 1 uses q=u_down-u_over with the reciprocal hinge reaction.
            # This constrained geometry does not solve mantle tractions.
            force = (self.effective_line_force[trench] if self.effective_subduction else
                     GRAVITY_M_S2*self.slab_load[trench]*math.sin(dip))
            direction = np.where((owners == self.bp[trench])[:, None], self.normal[trench],
                                 -self.normal[trench])
            value = CM_YR_M_S*(self.length_m[trench]*force)[:, None]*np.cross(self.radial[trench], direction)
            for k, owner in enumerate(owners):
                self._block(owner, value[k], pull)
                if self.effective_subduction and self.effective_carrier_alpha > 0.:
                    other = self.effective_carrier_owner[trench[k]]
                    self._block(other, -self.effective_carrier_alpha*value[k], reaction)
                if (not self.effective_subduction and
                        getattr(self, 'subduction_response_version', subduction_response_version(s)) == 1):
                    other = self.bq[trench[k]] if owner == self.bp[trench[k]] else self.bp[trench[k]]
                    # One source W*sin(dip)*(u_down-u_over), not a second slab
                    # or an empirical suction fraction. The reaction follows
                    # the imposed moving-hinge constraint (see design note).
                    self._block(other, -value[k], reaction)
            self.notes['slab_line_force_n_per_m_max'] = float(force.max(initial=0.))
            if not self.effective_subduction:
                self.notes['coupled_slab_excess_mass_kg'] = float(self.slab_load[trench]@self.length_m[trench])
                self.notes['slab_pull_depth_window_km'] = slab_memory.MAX_SLAB_DEPTH_KM
            self.notes['attached_trench_length_km'] = float(np.sum(self.length_m[trench])/1e3)
        if self.effective_subduction:
            self.notes['effective_subduction_version'] = 1
            self.notes['effective_subduction_force_n_per_m'] = float(
                s.effective_subduction_settings['force_n_per_m'])
            self.notes['effective_subduction_integrated_force_n'] = float(
                self.effective_line_force[trench]@self.length_m[trench])
            self.notes['effective_subduction_source'] = (
                'Prescribed horizontal traction delivered to incoming lithosphere; '
                'exchange with an unresolved slab/mantle reservoir. Basal, interface, '
                'hinge and collision resistance remain explicit; no slab/neck drag or upper driving reaction.')
            if self.effective_carrier_enabled:
                self.notes['effective_subduction_source'] = (
                    'Prescribed source f L (u_down - alpha u_carrier) at shared finite ports; '
                    'remaining reaction and supplied power belong to the unresolved slab/mantle reservoir. '
                    'Passive operators unchanged; actual overriding owner carries the trench; no independent hinge motion.')
                self.notes['effective_subduction_carrier_traction_alpha'] = self.effective_carrier_alpha
        if getattr(self, 'slab_tethers', False):
            pull = self.tether_assembly['down_drive'].copy()
            reaction = self.tether_assembly['over_drive'].copy()
            self.notes['slab_tether_channels'] = len(self.tether_assembly['channels'])
            self.notes['slab_line_force_n_per_m_max'] = float(self.tether_assembly['line_drives'].max(initial=0.))
        self.slab_down_drive, self.slab_over_drive = pull, reaction
        self.drivers['slab'] = pull+reaction
        self.torque += self.drivers['slab']
        self.drivers['ridge'] = self._ridge_push()
        self.torque += self.drivers['ridge']
        self.drivers['collision'] = self._collision_torque()
        self.torque += self.drivers['collision']

    def _ridge_push(self):
        """Distributed age-gradient body force over the ocean floor.

        Ridge push is not a push at a ridge. It is the horizontal gradient of the
        cooling plate's potential energy, spread over every ocean cell whose
        neighbours differ in age, and it is summed into a torque the same way any
        other body force would be. Continental cells contribute nothing here: the
        continental column's own potential is in the material functional, and
        adding a second continental GPE driver would double count it against
        gravitational_relaxation exactly as spending the collision cross term
        twice would.
        """
        s = self.s
        result = np.zeros(self.size)
        force = ridge_force_density(s)
        if force is None:
            return result
        coefficient = ridge_push_coefficient()
        points = np.asarray(s.xyz, float)
        ocean = np.asarray(s.crust) == 0
        lever = CM_YR_M_S*np.cross(points, force)*(np.asarray(s.cell_area, float)*1e6)[:, None]
        for plate in self.plates:
            index = self.slot[plate]
            result[3*index:3*index+3] = lever[s.plate == plate].sum(axis=0)
        self.notes['ridge_push_at_saturation_n_per_m'] = float(
            coefficient*RIDGE_PUSH_SATURATION_MYR*SECONDS_PER_MYR)
        self.notes['ridge_push_ocean_cells'] = int(ocean.sum())
        return result

    def _collision_torque(self):
        """The rigid share of the material gravitational functional.

        This is one driver, not two. gravitational_relaxation's potential holds
        both the self term (a thick column spreading under its own weight) and
        the distinct-sheet cross term (two stacked sheets pushing apart), and its
        per-plate rigid projection is exactly and only the cross term, because a
        rigid rotation of one plate's own vertices leaves its own face areas
        alone. So there is no separate continental GPE torque to add here, and
        the residual that relax spreads is the same potential's remainder.
        """
        import native_material_evolution
        import column_density
        result = np.zeros(self.size)
        mesh = getattr(self.s, 'material_surface', None)
        if not isinstance(mesh, dict) or not len(mesh.get('faces', ())):
            return result
        owner = np.asarray(mesh['vertex_owner'])
        if len(mesh['faces']) < 2 or len(np.unique(owner)) < 2:
            # A common rigid rotation preserves every self and cross area.
            # Internal GPE may still deform this sheet, but its net rigid
            # torque is exactly zero; no contact-history gate is involved.
            self.notes['collision_overlap_pairs'] = 0
            return result
        overlap = getattr(self.s, '_collision_overlap', None)
        _, gradient, _ = gravitational_relaxation.energy_gradient(
            mesh['vertices'], mesh['faces'], self.s.structure['thickness_km'],
            native_material_evolution.gravitational_reference(self.s),
            self.s.parcel_collision_sheet, radius=mesh.get('radius_km', RADIUS_KM), overlap=overlap,
            **column_density.options(self.s))
        partition = gravitational_relaxation.rigid_mode_partition(
            mesh['vertices'], mesh['faces'], mesh['area_km2'], gradient, owner)
        self.partition = partition['diagnostics']
        self.notes['collision_overlap_pairs'] = (0 if overlap is None
            else int(len(np.asarray(overlap['first']))))
        for plate, torque in zip(partition['owners'], partition['torque_n_m']):
            self._block(int(plate), torque*(CM_YR_M_S/RADIUS_M), result)
        return result

    # ----------------------------------------------------------- plastic terms
    def _plastic(self):
        s = self.s
        live = self.live
        if not len(live):
            # Material contacts can survive after one plate loses its last
            # dominant control-mesh cell. They still belong in the force solve.
            self._weld()
            return
        normal, tangent = self._relative_rows(live)
        self.relative_normal = normal
        self.relative_tangent = tangent
        age = .5*(np.asarray(s.age, float)[np.asarray(s.ba)[live]]
                  + np.asarray(s.age, float)[np.asarray(s.bb)[live]])
        continental = ((np.asarray(s.crust)[np.asarray(s.ba)[live]] > 0)
                       | (np.asarray(s.crust)[np.asarray(s.bb)[live]] > 0))
        depth = np.where(continental, CONTINENTAL_SEISMOGENIC_KM*1e3,
                         seismogenic_depth_m(age, TRANSFORM_DEPTH_CAP_KM))
        # Strike-slip on EVERY segment, not only on the ones a kinematic label
        # called a transform. Oblique margins partition their strain: Sumatra
        # slips along strike and subducts across it at the same time. Making the
        # tangential component cost something everywhere supports simultaneous
        # normal consumption when the normal-motion partition is selected.
        self.elements.append(dict(kind='strike_slip', shape='abs',
            rows=(tangent,), coefficient=TRANSFORM_SHEAR_PA*depth*self.length_m[live]*CM_YR_M_S,
            scale=np.ones(len(live)), edges=live))
        member = np.isin(live, self.trench_edges)
        if member.any():
            take = np.flatnonzero(member)
            self.elements.append(dict(kind='megathrust', shape='cone',
                rows=(normal[take], tangent[take]),
                coefficient=MEGATHRUST_N_PER_M*self.length_m[live[take]]*CM_YR_M_S,
                scale=np.ones(len(take)), edges=live[take]))
        rest = np.flatnonzero(~member)
        if len(rest):
            # Convergence away from a trench is taken up by distributed
            # shortening of the lithosphere itself, which costs the integrated
            # strength of the column. One-sided: it resists closing only.
            self.elements.append(dict(kind='compression', shape='negative',
                rows=(normal[rest],),
                coefficient=COMPRESSIVE_N_PER_M*self.length_m[live[rest]]*CM_YR_M_S,
                scale=np.ones(len(rest)), edges=live[rest]))
        self._weld()

    def _weld(self):
        """Select local traction or the legacy connected-patch coordinate.

        The legacy branch sums clipping derivatives within a patch before the law.
        Internal triangle edges cancel before resistance is evaluated, while
        disconnected opening and closing patches cannot cancel each other.
        The inherited line capacity and opening-only constitutive law remain
        unchanged. This reduced coordinate still cannot resolve opposing
        motions within one connected patch or attach a wholly buried sheet.
        Closing is handled elsewhere by GPE and compression; this element
        alone does not establish convergence arrest or a complete work budget.
        """
        if getattr(self.s, 'suture_weld_coordinate_version', 0) == 1:
            self._local_weld()
            return
        if getattr(self.s, 'suture_weld_coordinate_version', 0) != 0:
            raise ValueError('Unsupported suture weld coordinate version.')
        s = self.s
        self.weld_rows = []
        rows = collision_contacts.weld_rows(s)
        if not rows:
            return
        mesh = s.material_surface
        overlap = getattr(s, '_collision_overlap', None)
        if overlap is None or not len(np.asarray(overlap['first'])):
            return
        first, second = np.asarray(overlap['first']), np.asarray(overlap['second'])
        sheets = np.asarray(s.parcel_collision_sheet)
        import collision_fronts
        force_overlap = gravitational_relaxation._physical_overlap(
            mesh['vertices'], mesh['faces'], sheets, mesh.get('radius_km', RADIUS_KM), overlap)
        force_first, force_second = force_overlap['first'], force_overlap['second']
        force_geometry = collision_fronts.prepare(mesh, sheets, force_overlap)
        modes = gravitational_relaxation.overlap_area_rigid_modes(
            mesh['vertices'], mesh['faces'], force_first, force_second, np.asarray(mesh['vertex_owner']),
            radius=mesh.get('radius_km', RADIUS_KM))
        pair = np.sort(np.column_stack((sheets[first], sheets[second])), axis=1)
        force_pair = np.sort(np.column_stack((sheets[force_first], sheets[force_second])), axis=1)
        index = {}
        for position, key in enumerate(map(tuple, pair)):
            index.setdefault(key, []).append(position)
        linear, coefficient, delta_scale, records = [], [], [], []
        for row, top, under in rows:
            take = index.get(tuple(sorted((int(row['top_sheet']), int(row['under_sheet'])))))
            if not take:
                continue
            fronts = row.get('local_fronts', ())
            covered = [int(i) for front in fronts for i in front['overlap_indices']]
            if len(covered) != len(set(covered)) or set(covered) != set(take):
                raise ValueError('Weld fronts must partition the current physical overlap ledger.')
            key = np.sort([int(row['top_sheet']), int(row['under_sheet'])])
            force_take = np.flatnonzero(np.all(force_pair == key, axis=1))
            groups = collision_fronts.force_stencil_groups(mesh, sheets, overlap, fronts,
                force_overlap, force_take, geometry=force_geometry)
            capacity = self._weld_capacity(row, top, under)
            for front, take in zip(fronts, groups):
                operator = np.zeros(self.size)
                for owners, vectors in ((modes['owner_first'][take], modes['mode_first'][take]),
                                        (modes['owner_second'][take], modes['mode_second'][take])):
                    for owner in np.unique(owners):
                        self._block(int(owner), vectors[owners == owner].sum(axis=0), operator)
                # dA/dt in m^2/s for x in cm/yr-scaled rotation units.
                operator *= (CM_YR_M_S/RADIUS_M)*1e6
                trace_km = float(front.get('length_km', 0.))
                if trace_km <= 0. or not np.any(operator):
                    continue
                linear.append(operator)
                coefficient.append(capacity)
                delta_scale.append(trace_km*1e3*CM_YR_M_S)
                records.append(dict(contact_id=int(row['id']), top_owner=int(top), under_owner=int(under),
                    front_index=int(front['front_index']), front_center=list(front['center']),
                    coordinate='connected physical overlap patch area',
                    trace_length_km=trace_km, capacity_n_per_m=capacity,
                    overlap_area_km2=float(front['overlap_area_km2']),
                    weld_cohesion=float(row.get('weld_cohesion', 1.)),
                    idle_myr=float(s.t)-float(row.get('last_convergent_myr', s.t))))
        if not linear:
            return
        self.weld_rows = records
        self.elements.append(dict(kind='suture_weld', shape='negative',
            rows=(np.asarray(linear),), coefficient=np.asarray(coefficient),
            scale=np.asarray(delta_scale), edges=None))

    def _local_weld(self):
        """Integrate the opening law locally before summing force and torque."""
        import collision_fronts
        import weld_geometry
        s = self.s
        self.weld_rows = []
        rows = collision_contacts.weld_rows(s)
        overlap = getattr(s, '_collision_overlap', None)
        if not rows or overlap is None or not len(overlap['first']):
            return
        mesh = s.material_surface
        sheets = np.asarray(s.parcel_collision_sheet)
        geometry = overlap.get('_front_geometry')
        if geometry is None:
            geometry = collision_fronts.prepare(mesh, sheets, overlap)
        pair = np.sort(np.column_stack((sheets[overlap['first']], sheets[overlap['second']])), axis=1)
        linear, coefficients, bounds = [], [], []
        for row, top, under in rows:
            key = np.sort([int(row['top_sheet']), int(row['under_sheet'])])
            selected = np.flatnonzero(np.all(pair == key, axis=1))
            fronts = row.get('local_fronts', ())
            covered = [int(i) for front in fronts for i in front['overlap_indices']]
            if len(covered) != len(set(covered)) or set(covered) != set(selected):
                raise ValueError('Weld fronts must partition the current physical overlap ledger.')
            capacity = self._weld_capacity(row, top, under)
            for front in fronts:
                arcs = weld_geometry.arcs(mesh, sheets, overlap, front, row['top_sheet'], geometry)
                for arc in arcs:
                    normal, side, length = arc['normal'], arc['side'], arc['length_km']
                    # omega x r dotted with outward normal. Opposite plate
                    # blocks enforce action/reaction and zero common rotation.
                    modes = (np.cross(np.array([arc['basis'], arc['tangent']]), normal)
                             *float(mesh.get('radius_km', RADIUS_KM))/RADIUS_KM)
                    if side:
                        modes = -modes
                    operator = np.zeros((2, self.size))
                    for component, mode in enumerate(modes):
                        self._block(top, mode, operator[component])
                        self._block(under, -mode, operator[component])
                    linear.append(operator)
                    coefficients.append(capacity*.5*float(mesh.get('radius_km', RADIUS_KM))*1e3*CM_YR_M_S)
                    bounds.append([arc['start'], arc['end']])
                    midpoint = .5*(arc['start']+arc['end'])
                    point = math.cos(midpoint)*arc['basis']+math.sin(midpoint)*arc['tangent']
                    self.weld_rows.append(dict(contact_id=int(row['id']), top_owner=int(top), under_owner=int(under),
                        front_index=int(front['front_index']), front_center=point.tolist(),
                        coordinate='local physical free-edge normal velocity', side=int(side),
                        trace_length_km=float(length), capacity_n_per_m=capacity,
                        integration='analytic great-circle unilateral Huber law',
                        weld_cohesion=float(row.get('weld_cohesion', 1.)),
                        idle_myr=float(s.t)-float(row.get('last_convergent_myr', s.t))))
        if linear:
            self.elements.append(dict(kind='suture_weld', shape='arc_opening', rows=(np.asarray(linear),),
                coefficient=np.asarray(coefficients), bounds=np.asarray(bounds),
                scale=np.ones(len(linear)), edges=None))

    def _weld_capacity(self, row, top, under):
        """F_REF x the trace's own strength x the contact's thermal/anneal state."""
        boundary = np.flatnonzero(((self.bp == top) & (self.bq == under))
                                  | ((self.bp == under) & (self.bq == top)))
        if len(boundary) and self.length_m[boundary].sum() > 0.:
            sample = float(np.average(self.strength[boundary], weights=self.length_m[boundary]))
        else:
            sample = 1.
        reference = min(enhanced_rifting.F_REF_N_PER_M*sample, WELD_CAPACITY_CAP_N_PER_M)
        return float(reference*collision_contacts.weld_capacity_factor(row, self.s.t))

    # ------------------------------------------------------------------- solve
    def _row_rates(self, operator, x):
        """Constitutive velocities; reduced modes preserve native common width."""
        return operator@x

    def _evaluate(self, x, delta, want_derivatives=True):
        value = .5*x@self.stiffness@x-self.torque@x
        gradient = self.stiffness@x-self.torque if want_derivatives else None
        force_reference = np.abs(self.stiffness)@np.abs(x)+np.abs(self.torque) if want_derivatives else None
        hessian = self.stiffness.copy() if want_derivatives else None
        parts = {}
        if len(self.hinge_coefficient):
            speed = self._row_rates(self.hinge, x)
            closing = np.minimum(speed, 0.)
            weight = self.hinge_coefficient
            parts['hinge'] = float(.5*np.sum(weight*closing*closing))
            value += parts['hinge']
            if want_derivatives:
                gradient += (weight*closing)@self.hinge
                force_reference += np.abs(weight*closing)@np.abs(self.hinge)
                active = self.hinge[closing < 0.]
                if len(active):
                    hessian += np.einsum('e,ei,ej->ij', weight[closing < 0.], active, active)
        yielded = {}
        version = getattr(self, 'resistance_version', 0)
        for element in self.elements:
            if element['shape'] == 'arc_opening':
                import weld_geometry
                work = 0.; count = 0
                for operator, coefficient, (start, end) in zip(element['rows'][0], element['coefficient'], element['bounds']):
                    term, first, second, opening = weld_geometry.integrate(operator, x, start, end, delta,
                        velocity=self._row_rates(operator, x))
                    work += coefficient*term
                    count += int(opening > 3.*delta*(end-start))
                    if want_derivatives:
                        gradient += coefficient*first
                        force_reference += np.abs(coefficient*first)
                        hessian += coefficient*second
                parts[element['kind']] = work
                yielded[element['kind']] = count
                value += work
                continue
            width = delta*element['scale']
            coefficient = element['coefficient']
            if element['shape'] == 'cone':
                normal, tangent = element['rows']
                opening, tangential = self._row_rates(normal, x), self._row_rates(tangent, x)
                closed, first, second = _cone_closing_terms(opening, width, version)
                magnitude = np.sqrt(closed*closed+tangential*tangential+width*width)
                # The quotient avoids subtracting nearly equal numbers at
                # tiny rates. Keep the historical arithmetic for version 0.
                potential = ((closed*closed+tangential*tangential)/(magnitude+width)
                             if version == 1 else magnitude-width)
                parts[element['kind']] = float(np.sum(coefficient*potential))
                value += parts[element['kind']]
                yielded[element['kind']] = int(np.count_nonzero(magnitude > 3.*width))
                if want_derivatives:
                    jn = first[:, None]*normal
                    direction = (closed[:, None]*jn+tangential[:, None]*tangent)/magnitude[:, None]
                    gradient += coefficient@direction
                    force_reference += np.abs(coefficient)@np.abs(direction)
                    weight = coefficient/magnitude
                    hessian += np.einsum('e,ei,ej->ij', weight, jn, jn)
                    hessian += np.einsum('e,ei,ej->ij', weight, tangent, tangent)
                    hessian += np.einsum('e,ei,ej->ij', weight*closed*second, normal, normal)
                    hessian -= np.einsum('e,ei,ej->ij', coefficient/magnitude, direction, direction)
                continue
            (operator,) = element['rows']
            rate = self._row_rates(operator, x)
            if element['shape'] == 'abs':
                term, first, second = _abs_terms(rate, width)
                yielded[element['kind']] = int(np.count_nonzero(np.abs(rate) > 3.*width))
            else:
                law = _passive_negative_terms if version == 1 else _negative_terms
                term, first, second = law(rate, width)
                yielded[element['kind']] = int(np.count_nonzero(rate < -3.*width))
            parts[element['kind']] = float(np.sum(coefficient*term))
            value += parts[element['kind']]
            if want_derivatives:
                gradient += (coefficient*first)@operator
                force_reference += np.abs(coefficient*first)@np.abs(operator)
                hessian += np.einsum('e,ei,ej->ij', coefficient*second, operator, operator)
        if want_derivatives:
            self._reference_gradient=gradient
            self._force_reference=force_reference
        return value, gradient, hessian, parts, yielded

    def _resistance_work(self, x, delta):
        """Actual local resisting power, distinct from the solver potential.

        No values are clipped: historical active tails and any unexpected
        negative local work remain visible in the diagnostics.
        """
        parts, local_work = {}, []
        if len(self.hinge_coefficient):
            closing = np.minimum(self._row_rates(self.hinge, x), 0.)
            work = self.hinge_coefficient*closing*closing
            parts['hinge'] = float(work.sum())
            local_work.extend(work)
        version = getattr(self, 'resistance_version', 0)
        for element in self.elements:
            coefficient = element['coefficient']
            if element['shape'] == 'arc_opening':
                import weld_geometry
                work = np.asarray([weight*(weld_geometry.integrate(operator, x, start, end, delta,
                    velocity=self._row_rates(operator, x))[1]@x)
                    for operator, weight, (start, end) in zip(element['rows'][0], coefficient, element['bounds'])])
            else:
                width = delta*element['scale']
                if element['shape'] == 'cone':
                    normal, tangent = element['rows']
                    opening, tangential = self._row_rates(normal, x), self._row_rates(tangent, x)
                    closed, first, _ = _cone_closing_terms(opening, width, version)
                    magnitude = np.sqrt(closed*closed+tangential*tangential+width*width)
                    work = coefficient*(opening*closed*first+tangential*tangential)/magnitude
                else:
                    rate = self._row_rates(element['rows'][0], x)
                    law = (_abs_terms if element['shape'] == 'abs' else
                           _passive_negative_terms if version == 1 else _negative_terms)
                    work = coefficient*rate*law(rate, width)[1]
            parts[element['kind']] = parts.get(element['kind'], 0.)+float(work.sum())
            local_work.extend(work)
        local_work = np.asarray(local_work)
        return parts, dict(minimum_local_resisting_work_w=float(local_work.min(initial=0.)),
                           negative_resisting_work_elements=int(np.count_nonzero(local_work < 0.)))

    def _warm_start(self):
        """SPD secant linearisation of every plastic element, solved once."""
        linear = self.stiffness.copy()
        if len(self.hinge_coefficient):
            linear += np.einsum('e,ei,ej->ij', self.hinge_coefficient, self.hinge, self.hinge)
        for element in self.elements:
            if element['shape'] == 'arc_opening':
                import weld_geometry
                for operator, coefficient, (start, end) in zip(element['rows'][0], element['coefficient'], element['bounds']):
                    second = weld_geometry.moments(start, end)[1]
                    linear += coefficient/SECANT_REFERENCE_CM_YR*(operator.T@second@operator)
                continue
            reference = np.maximum(SECANT_REFERENCE_CM_YR*element['scale'], 1e-30)
            weight = element['coefficient']/reference
            for operator in element['rows']:
                linear += np.einsum('e,ei,ej->ij', weight, operator, operator)
        return self._solve_spd(linear, self.torque), linear

    @staticmethod
    def _solve_spd(matrix, rhs):
        """Equilibrate units without adding fictitious drag to free modes."""
        diagonal = np.diag(matrix)
        if not np.isfinite(matrix).all() or np.any(diagonal <= 0.):
            raise ValueError('Plate balance has an unresisted or invalid active mode.')
        scale = np.sqrt(diagonal)
        normalized = matrix/scale[:, None]/scale[None, :]
        try:
            factor = np.linalg.cholesky(.5*(normalized+normalized.T))
            result = np.linalg.solve(factor.T, np.linalg.solve(factor, rhs/scale))/scale
        except np.linalg.LinAlgError as error:
            raise ValueError('Plate balance resistance is not positive definite.') from error
        if not np.isfinite(result).all():
            raise ValueError('Plate balance produced a nonfinite solution.')
        return result

    def _relative_residual(self, gradient):
        # Test every plate, including small fractional footprints that a global
        # torque norm can conceal. The basal metric also equilibrates units.
        scale = np.sqrt(np.diag(self.stiffness))
        if np.any(scale <= 0.):
            raise ValueError('Plate balance has an unresisted active mode.')
        residual = (gradient/scale).reshape(-1, 3)
        if gradient is getattr(self,'_reference_gradient',None):
            # Relative backward error against the actual force contributions,
            # independently for each plate. An external driver can vanish at
            # detachment while viscous and regularized contact forces balance.
            # Dividing only by that vanishing driver demands impossible precision.
            reference=(self._force_reference/scale).reshape(-1,3)
            numerator=np.linalg.norm(residual,axis=1)
            denominator=np.linalg.norm(reference,axis=1)
            ratio=np.divide(numerator,denominator,out=np.full_like(numerator,np.inf),where=denominator>0.)
            ratio[(numerator==0.) & (denominator==0.)]=0.
            return float(ratio.max(initial=0.))
        drive = (self.torque/scale).reshape(-1, 3)
        reference = max(float(np.linalg.norm(drive, axis=1).max(initial=0.)), 1e-30)
        return float(np.linalg.norm(residual, axis=1).max(initial=0.)/reference)

    def solve(self):
        if not self.size:
            return np.zeros(0), {}
        x, linear = self._warm_start()
        import numerical_accuracy
        force_tolerance=(numerical_accuracy.OUTER_RELATIVE_TOLERANCE if numerical_accuracy.version(self.s)
            else FORCE_RELATIVE_TOLERANCE)
        iterations, backtracks = 0, 0
        for delta in np.asarray(HUBER_CONTINUATION_KM_MYR, float)*KM_MYR_CM_YR:
            for _ in range(MAX_NEWTON_ITERATIONS):
                value, gradient, hessian, _, _ = self._evaluate(x, delta)
                current_residual = self._relative_residual(gradient)
                if current_residual <= force_tolerance:
                    break
                step = self._solve_spd(hessian, -gradient)
                slope = float(gradient@step)
                if slope > 0.:
                    step, slope = -gradient, -float(gradient@gradient)
                alpha = 1.
                accepted = False
                while alpha > 1e-14:
                    trial = self._evaluate(x+alpha*step, delta, want_derivatives=False)[0]
                    if trial <= value+ARMIJO*alpha*slope:
                        accepted = True
                        break
                    # Near the minimizer, subtracting large potentials can
                    # bury the predicted decrease in floating-point roundoff.
                    # Only in that energy-resolution band, use independently
                    # evaluated force improvement to accept the Newton step.
                    roundoff = 8.*np.finfo(float).eps*max(abs(value), abs(trial), 1.)
                    if (np.isfinite(trial) and -alpha*slope <= roundoff
                            and trial <= value+roundoff):
                        trial_gradient = self._evaluate(x+alpha*step, delta)[1]
                        if self._relative_residual(trial_gradient) < (1.-ARMIJO*alpha)*current_residual:
                            accepted = True
                            break
                    alpha *= .5
                    backtracks += 1
                if not accepted:
                    raise ValueError('Plate balance line search failed; step rejected.')
                x = x+alpha*step
                iterations += 1
        gradient = self._evaluate(x, HUBER_CONTINUATION_KM_MYR[-1]*KM_MYR_CM_YR)[1]
        residual = self._relative_residual(gradient)
        if residual > force_tolerance:
            raise ValueError(f'Plate balance did not converge: scaled residual {residual:g}; step rejected.')
        self.x = x
        self.iterations, self.backtracks = iterations, backtracks
        self.linear = linear
        return x

    # ------------------------------------------------------------- diagnostics
    def rotation(self):
        """Angular velocity in rad/Myr for every plate row, inactive rows zero."""
        omega = np.zeros_like(self.s.omega)
        factor = CM_YR_M_S/RADIUS_M*SECONDS_PER_MYR
        for plate, index in self.slot.items():
            omega[plate] = self.x[3*index:3*index+3]*factor
        return omega

    def diagnostics(self, omega):
        s = self.s
        if getattr(self, 'slab_tethers', False):
            import slab_tether_forces
            self.notes['slab_tether_power'] = slab_tether_forces.audit(self.tether_assembly, self.x)
            self.notes['condensed_slab_velocity_quadratic_w'] = float(self.x@self.tether_assembly['stiffness']@self.x)
            self.notes['slab_power_interpretation'] = ('The condensed velocity quadratic is not total physical slab dissipation; '
                'slab_tether_power recovers mantle and neck dissipation from the eliminated velocities.')
        value, gradient, _, parts, yielded = self._evaluate(self.x, HUBER_CONTINUATION_KM_MYR[-1]*KM_MYR_CM_YR)
        work, passivity = self._resistance_work(self.x, HUBER_CONTINUATION_KM_MYR[-1]*KM_MYR_CM_YR)
        viscous_work = float(self.x@self.stiffness@self.x)
        driver_work = float(self.torque@self.x)
        total_work = viscous_work+sum(work.values())
        speeds, rms = {}, {}
        for plate in self.plates:
            fraction = self._support(plate)
            select = fraction > 0.
            if not np.any(select):
                continue
            velocity = np.linalg.norm(np.cross(omega[plate], np.asarray(s.xyz)[select])*RADIUS_KM, axis=1)*KM_MYR_CM_YR
            weight = np.asarray(s.cell_area, float)[select]*fraction[select]
            rms[str(s.names[plate])] = float(np.sqrt(np.average(velocity**2, weights=weight)))
            speeds[str(s.names[plate])] = float(np.average(velocity, weights=weight))
        rotation, spin = net_rotation_deg_myr(s, omega)
        scale = max(float(np.linalg.norm(self.torque)), 1e-300)
        drive = {}
        for name, vector in self.drivers.items():
            drive[name] = {str(s.names[p]): float(np.linalg.norm(vector[3*i:3*i+3])*RADIUS_M/CM_YR_M_S)
                           for p, i in self.slot.items()}
        weld = []
        element = next((e for e in self.elements if e['kind'] == 'suture_weld'), None)
        for position, record in enumerate(self.weld_rows if element is not None else ()):
            if element['shape'] == 'arc_opening':
                import weld_geometry
                start, end = element['bounds'][position]
                delta = HUBER_CONTINUATION_KM_MYR[-1]*KM_MYR_CM_YR
                term, derivative, _, opening = weld_geometry.integrate(element['rows'][0][position], self.x, start, end, delta)
                weld.append(dict(record, mean_opening_speed_km_myr=opening/(end-start)/KM_MYR_CM_YR,
                    resisting_work_w=float(element['coefficient'][position]*(derivative@self.x)),
                    dissipation_potential_w=float(element['coefficient'][position]*term),
                    at_yield=bool(opening > 3.*delta*(end-start))))
                continue
            rate = float(element['rows'][0][position]@self.x)
            length = max(record['trace_length_km']*1e3, 1e-30)
            weld.append(dict(record, overlap_area_rate_km2_myr=rate*SECONDS_PER_MYR/1e6,
                normal_rate_cm_yr=-rate/length/CM_YR_M_S,
                at_yield=bool(rate < -3.*HUBER_CONTINUATION_KM_MYR[-1]*KM_MYR_CM_YR*element['scale'][position])))
        if self.effective_subduction and self.effective_carrier_enabled:
            import effective_subduction_carrier_traction as carrier
            self.notes['effective_subduction_carrier_power'] = carrier.source_audit(self, self.x)
        return dict(version=VERSION, model='inertia-free instantaneous Stokes torque balance',
            subduction_response_version=self.subduction_response_version,
            subduction_response=('effective incoming and reduced real-carrier traction; no independent hinge motion'
                                 if self.effective_subduction and self.effective_carrier_alpha > 0. else
                                 'effective one-sided trench traction; upper motion from its own forces and coupling'
                                 if self.effective_subduction else
                                 'moving hinge carried by overriding plate; independently eliminated attached slab velocity'
                                 if self.subduction_response_version and self.slab_tethers else
                                 'moving hinge carried by overriding plate; constrained fixed-dip energy closure'
                                 if self.subduction_response_version else
                                 'fixed-hinge experiment with independently eliminated slab velocities'
                                 if self.slab_tethers else 'historical fixed-trench slab work'),
            slab_power_w=dict(downgoing=float(self.slab_down_drive@self.x),
                              overriding=float(self.slab_over_drive@self.x),
                              total=float(self.drivers['slab']@self.x)),
            slab_power_note=('Effective traction power from an unresolved reservoir, not resolved slab gravitational power.'
                if self.effective_subduction else 'Components partition the single slab driver; do not add them to its total.'),
            slab_power_by_plate_w={str(s.names[p]): dict(
                downgoing=float(self.slab_down_drive[3*i:3*i+3]@self.x[3*i:3*i+3]),
                overriding=float(self.slab_over_drive[3*i:3*i+3]@self.x[3*i:3*i+3]))
                for p, i in self.slot.items()},
            slab_stokes_dissipation_w=(self.notes['slab_tether_power']['mantle_dissipation_w']
                if self.slab_tethers else float(self.slab_stokes_coefficient@(
                (self.slab_horizontal_rows@self.x)**2+(self.slab_vertical_rows@self.x)**2))),
            slab_anchor_dissipation_w=float(self.slab_anchor_coefficient@(self.slab_anchor_rows@self.x)**2),
            plate_resistance_version=getattr(self, 'resistance_version', 0),
            resistance_law=('passive one-sided compression and megathrust' if getattr(self, 'resistance_version', 0) == 1
                            else 'historical smooth-tail law; can supply negative resisting work'),
            plates=[str(s.names[p]) for p in self.plates],
            mean_speed_cm_yr=speeds, rms_speed_cm_yr=rms,
            fastest_plate_cm_yr=float(max(rms.values(), default=0.)),
            net_rotation_deg_myr=rotation, net_rotation_bound_deg_myr=NET_ROTATION_BOUND_DEG_MYR,
            net_rotation_axis=spin.tolist(),
            newton_iterations=self.iterations, newton_backtracks=self.backtracks,
            relative_gradient_norm=float(np.linalg.norm(gradient)/scale),
            scaled_force_residual=self._relative_residual(gradient),
            force_relative_tolerance=(__import__('numerical_accuracy').OUTER_RELATIVE_TOLERANCE
                if __import__('numerical_accuracy').version(s) else FORCE_RELATIVE_TOLERANCE),
            force_residual_normalization='per-plate backward error against assembled force contributions',
            basal_footprint='transported fractional plate support',
            objective_w=float(value), dissipation_w=work, dissipation_potential_w=parts,
            dissipation_definition='Actual local resisting work x.grad(D); viscous work reported separately.',
            total_resisting_work_w=float(total_work), power_balance_error_w=float(total_work-driver_work),
            basal_dissipation_w=float(sum(
                self.x[3*self.slot[p]:3*self.slot[p]+3]@block@self.x[3*self.slot[p]:3*self.slot[p]+3]
                for p, block in self.basal.items())),
            viscous_dissipation_w=viscous_work,
            interface_shear_dissipation_w=float(self.x@getattr(self, 'interface_stiffness', np.zeros_like(self.stiffness))@self.x),
            driver_work_w=driver_work,
            driver_torque_n_m=drive, elements_at_yield=yielded,
            welded_traces=weld, suture_weld_elements=len(self.weld_rows),
            rigid_mode_partition=getattr(self, 'partition', None),
            asthenosphere_drag_pa_s_m=ASTHENOSPHERE_DRAG_PA_S_M,
            huber_continuation_km_myr=list(HUBER_CONTINUATION_KM_MYR),
            regularization_note='Finite smoothing; a converged force residual does not establish the plastic limit.',
            inertia='none: omega is solved from the instantaneous balance, never relaxed toward it',
            **passivity, **self.notes)


def solve(s, dt):
    """Solve this step's balance. Returns (omega array, diagnostics); never writes s."""
    if not np.isscalar(dt) or not np.isfinite(dt) or dt <= 0:
        raise ValueError('The plate balance needs a finite positive interval.')
    model = Balance(s, dt)
    model.solve()
    omega = model.rotation()
    return omega, model.diagnostics(omega)
